### ISSUE TITLE
Implement DLSS + LOD bias

### ISSUE THREAD

**Issue by Pacoboyd** [yamashi/CyberEngineTweaks#189]
Is this something that could be implemented?  Seems CDPR forgot to implement the DLSS LOD bias of -3 in their profile.  See reddit link here and associated link in post.

https://www.reddit.com/r/nvidia/comments/kf52ag/gn_cyberpunk_2077_dlss_quality_comparison_vs/gg6m9km/

Detail is greatly enhanced when using DLSS with LOD Bias -3

**Comment by emoose** [comment]
Apparently 1.05 added a new "DLSS/EnableCustomMipBias" INI setting (default true), maybe it's now fixed already?

**Comment by Pacoboyd** [comment]
Hmm, interesting, one wonders what value that is pulling and where it's pulling it from.  If its supposed to be using the nvidia profile, then even after 1.05 it was showing as 0.

I will do some testing with the inspector setting to see if setting it there has any additional perceptible effect on 1.05

**Comment by Pacoboyd** [comment]
Made the following comparison in 1.05.  To me at least there does appear to be a perceptible difference especially in some of the finer details such as fence sharpness and scaffolding sharpness.  The LOD 0 has a slight blurriness in some of the details.

https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=d8f5828c-439c-11eb-83c8-ebb5d6f907df

**Comment by emoose** [comment]
Had a quick look at what's checking the EnableCustomMipBias value, seems that with that enabled the bias is maybe being set to -1:
![ida64_2020_12_21-19_27](https://user-images.githubusercontent.com/1755499/102814495-a40d8d00-43c2-11eb-8255-297fd14953a2.png)

Since EnableCustomMipBias is defaulted to true we could maybe patch the -1 value there to whatever we liked, so nvidia inspector wouldn't be needed. Maybe something for someone that has DLSS support to look into.
