### ISSUE TITLE
Console not showing up, 

### ISSUE THREAD

**Issue by Jvints** [yamashi/CyberEngineTweaks#228]
So I ran the engine and no fail. So I'm a little lost on what I need to do? Did I miss something?

**Comment by CCWBee** [comment]
I'm having the same issue, although also i'm finding when i disable the boundary teleport in the config that also does nothing, otherwise the logs there and the intro skips but it just seems thats it

**Comment by usercologne** [comment]
Same with me.
Got two warnings (spectre patch failed due to unknown version and virtual input patch failed) other than that looking good.
But nothing happens, intro is shown (though logs say it's patched) and no chance of a console whatsoever. If it weren't for the logs I would say the mod ain't installed.

v1.05 GOG Version, did the AMD/ SMT patch myself. Also altered the memory_pool_budget myself in v1.04, which is no longer there in v1.05.

**Comment by LulzRose** [comment]
> Got two warnings (spectre patch failed due to unknown version and virtual input patch failed) other than that looking good.
Spectre is correct unless you are running an intel CPU and virtual input only applies to controller users. Also regarding the console, is it enabled in the config file?

**Comment by usercologne** [comment]
> Spectre is correct unless you are running an intel CPU and virtual input only applies to controller users. Also regarding the console, is it enabled in the config file?

I'm running an Intel CPU but an old one, maybe there's no fix for this specific generation (Sandy Bridge).
Yes the console is enabled.

Problem solved, tilde '~' doesn't work for ISO keyboards as it's positioned way other. Switched it to key 190 ('.'), which is located the same way on ANSI & ISO keyboards.

Maybe a hint in the description would help, there're a lot of ISO users around the world ;)

**Comment by MxZeal** [comment]
I have had this problem for the past view versions now, but I do NOT have an ISO keyboard so that cannot be my issue. I'm not sure I kinda just gave up tho.

**Comment by skeith** [comment]
I have this issue too.
I am using International US Keyboard layout and pressing tilde `~` do nothing
Logs shows nothing related to it
