### ISSUE TITLE
Game image freezes when console is true

### ISSUE THREAD

**Issue by Pipodi** [yamashi/CyberEngineTweaks#283]
Title. 

If I alt-tab, the image "refreshes" itself, but it freezes instantly.

This is the log.

```
[2020-12-24 18:37:28.667] [info] Game version 1.06
[2020-12-24 18:37:28.668] [warning] 	Spectre patch: failed, unknown version
[2020-12-24 18:37:28.695] [warning] 	Virtual Input Patch: failed
[2020-12-24 18:37:28.740] [info] 	Start screen patch: success
[2020-12-24 18:37:28.809] [info] 	Hidden options hook: success
[2020-12-24 18:37:28.840] [info] 	Hook mouse clip function!
[2020-12-24 18:37:28.862] [info] 	Log function hook complete!
[2020-12-24 18:37:28.885] [info] 	LogChannel function hook complete!
[2020-12-24 18:37:28.956] [info] 	TDBID::ctor function hook complete!
[2020-12-24 18:37:29.023] [info] 	TDBID::ctor[CString] function hook complete!
[2020-12-24 18:37:29.090] [info] 	TDBID::ctor[Derive] function hook complete!
[2020-12-24 18:37:29.158] [info] 	TDBID::ctor[Unknown] function hook complete!
[2020-12-24 18:37:29.191] [info] 	TDBID::ToStringDEBUG function hook complete!
[2020-12-24 18:37:29.518] [info] 	D3D12 hook complete

====== ALT-F4 on frozen Cyberpunk, set console to false =======

[2020-12-24 18:38:14.538] [info] Game version 1.06
[2020-12-24 18:38:14.539] [warning] 	Spectre patch: failed, unknown version
[2020-12-24 18:38:14.565] [warning] 	Virtual Input Patch: failed
[2020-12-24 18:38:14.621] [info] 	Start screen patch: success
[2020-12-24 18:38:14.689] [info] 	Hidden options hook: success
```

Config:

```
{
    "avx": false,
    "console": false,
    "console_key": 192,
    "cpu_memory_pool_fraction": 0.5,
    "disable_antialiasing": false,
    "disable_async_compute": false,
    "disable_boundary_teleport": false,
    "disable_intro_movies": false,
    "disable_vignette": false,
    "dump_game_options": false,
    "enable_debug": false,
    "gpu_memory_pool_fraction": 1.0,
    "memory_pool": true,
    "remove_pedestrians": false,
    "skip_start_menu": true,
    "smt": false,
    "spectre": true,
    "virtual_input": true
}
```

i7 8770k + RTX 2080

**Comment by dwasss** [comment]
Same here

**Comment by ipoopedmypantsuups** [comment]
You have 2 choices here:

1. Run the game in windowed, or borderless windowed. console works then =)
2. Turn console=false. Console will be disabled but your game will run
Choices, choices...

**Comment by Pipodi** [comment]
Running on Windows or borderless window decreases performance, which is vital on a demanding game like this one. I prefer turning the console off, I don't use it either. I was just reporting the issue, maybe someone uses it for debuging purpose.

**Comment by skeevy420** [comment]
> 
> 
> You have 2 choices here:
> 
>     1. Run the game in windowed, or borderless windowed. console works then =)
> 
>     2. Turn console=false. Console will be disabled but your game will run
>        Choices, choices...

For me the console works on Fullscreen in 1080p on a 4K monitor.  However, every now and then when I open Cyberpunk I'll get the exact same freeze with audio issue.  I just ALT+F4 out, restart the game, and it'll work.  It seems to happen more often when disable_intro_movies is set to true. Here's my config if it'll help.

```
{
    "avx": false,
    "console": true,
    "console_key": 192,
    "cpu_memory_pool_fraction": 0.5,
    "disable_antialiasing": false,
    "disable_async_compute": false,
    "disable_boundary_teleport": false,
    "disable_intro_movies": false,
    "disable_vignette": true,
    "dump_game_options": false,
    "enable_debug": false,
    "gpu_memory_pool_fraction": 1.0,
    "memory_pool": true,
    "remove_pedestrians": false,
    "skip_start_menu": true,
    "smt": false,
    "spectre": true,
    "virtual_input": false
}
```

**Comment by Pipodi** [comment]
I did restart once, problem was fixed. However, the second time didn't work and I had to turn off the console.

**Comment by skeevy420** [comment]
Yeah, it's like that for me too.  In my case I know I'm being effected as soon as I launch the game because the Steam controller popup will appear in the middle of the screen where a 1080p sized window placed in the upper left corner would be.  Once I see that the full screen switch doesn't happen correctly I restart and it usually works. 

What's odd is if I start the game from a cold boot this will happen.  Close out, restart, and it'll work.  If I stop and start the game within a few minutes it'll likely work.  If my system goes into any kind of standby it'll go back to this happening.  

It also seems to happen if I click play on the launcher and then do anything that'll minimize or inactive the window like clicking the desktop or another window.  I've noticed that the Steam controller popup happens in both the launcher and the game so I'm wondering if there's some issue that occurs when the launcher switches to the game.

Before posting this I wondered if there was a way to skip the launcher and there is.  Adding `--launcher-skip` to the launch options disables the launcher and seems to have fixed it for me.  I launched the game 3 times after a cold boot just fine.

**Comment by ipoopedmypantsuups** [comment]
Turn the game to windowed or borderless windowed, or disable console. Console does not work on full screen :(

**Comment by Pipodi** [comment]
> Before posting this I wondered if there was a way to skip the launcher and there is. Adding `--launcher-skip` to the launch options disables the launcher and seems to have fixed it for me. I launched the game 3 times after a cold boot just fine.

Just tried this with RTSS in background. Game launches, but if I try to call the console, the game crashes.

**Comment by skeevy420** [comment]
> 
> 
> > Before posting this I wondered if there was a way to skip the launcher and there is. Adding `--launcher-skip` to the launch options disables the launcher and seems to have fixed it for me. I launched the game 3 times after a cold boot just fine.
> 
> Just tried this with RTSS in background. Game launches, but if I try to call the console, the game crashes.

[That's a known issue.](https://github.com/yamashi/CyberEngineTweaks/issues/286)

If you run it without RTSS it should work.  It's also said that RTSS and the console will work at the same time if you start RTSS on the game's title screen.  I wouldn't know.  I don't have RTSS installed.

@ipoopedmypantsuups It works on full screen just fine for me, especially since passing `--launcher-skip`.  The console does have issues with other programs that create overlays like RTSS, MSI Afterburner, Steam, AMD Radeon, Reshade, etc, and I have experienced those, but I can assure you that it works just fine on full screen if no overlays are running (and with both Reshade and AMD Radeon running on my system).
