### ISSUE TITLE
Lua event handlers proposal

### ISSUE THREAD

**Issue by yamashi** [yamashi/CyberEngineTweaks#288]
Currently the only way to execute Lua is to manually call dofile/loadfile, this is far from perfect and is not enough to make a proper mod.

What we might want to do is add a global function `registerHandler` taking an event name as first param and a function as second parameter.

Sample usage would be:
```lua
registerHandler("update", function (delta) 
  print("Frame delta: " + delta)
end)

registerHandler("imgui", function (delta) 
  -- some imgui code
end)
```

This would require storing a list of functions to call for each event and actually firing the event in various places.

**Comment by willuwontu** [comment]
Mod files can also be loaded in like LUA libraries with `foo = require "path.foo"` and then later have the functions run with `foo.bar(baz)`. This just means that the only thing you need to worry about is providing the means to load them (autoexec should probably load the mods somehow).

Ideally, mods should be using the native events like `Game.GetPlayer():OnMeleeHitEvent()`, etc, and tweaking them to their needs. Otherwise, you'll have to recreate shells for event once again.

It would be possible to create a generic hook-up though with something like:

```LUA
-- Create a table to store all the functions mods wish to run off of our handles
ModHandles = {}
ModHandles.Triggers = {}
ModHandles.AnyHandle = "Any"

-- Add functions to our table for usage with handles
function ModHandles.AddHandle(string handle, func trigger)
    table.insert(ModHandles.Triggers, {handle = handle, trigger = trigger})
end

-- Run our functions when handles happen
function ModHandles.TriggeredHandle(string handle, args arg)
    for k, v in ipairs(ModHandles.Triggers) do
        if (v.handle == handle) or (v.handle == ModHandles.AnyHandle) then
            v.trigger(param)
        end
    end
end
```

You would then hook up the generic events with something like this:
```LUA
player = Game.GetPlayer()
player:OnMeleeHitHandle(function(arg) ModHandles.TriggeredHandle("PlayerMeleeHit", arg) end)
-- repeat with different handles for each native event
```

**Comment by WSSDude420** [comment]
I believe we already have at least some support in regards to this as a whole so we may close this i suppose @yamashi ?
