### ISSUE TITLE
GPU crash when activating console

### ISSUE THREAD

**Issue by DrStalker** [yamashi/CyberEngineTweaks#319]
Windows 10 x64, CP2077 1.06 GoG in Borderless Window mode, CyberEngineTweaks v1.7.1, RX 570 graphics card with latest drivers,

Not running: (I checked these after other comments about crashes)  Rivatuner, Reshade, Discord overlay, Steam overlay, Gog Overlay

As soon as I push tilde to enable the console my PC locks up, then the game crashes.  Looking  at the CP2077 crash report this is a GPU crash: 

**stacktrace.txt:**

```
Error reason: Assert
Expression: <Unknown>
Message: Gpu Crash for unknown reasons! Callstack here is probably irrelevant. Check if Breadcrumbs or Aftermath logged anything useful.
File: e:\r6.patch0hotfix2\dev\src\common\gpuapi\src\dx12\gpuapidx12error.cpp(40)
```

**gpucrash-<date>.txt:**

Full content here:  https://pastebin.com/raw/haeRrv4Z

Any ideas what else to check for, or what to adjust to fix the crash?

**Comment by WSSDude420** [comment]
Seems to be exact same issue @TheChief5055 had (he put it inside one of a now closed issue that was unrelated to his in the end)
And yes if you read it Chief, didn't forget... Just cannot tell what exactly is wrong, as it literally crashes inside AMD driver, checking out the memdump you sent...

#280 (for reference, last few comments there)

Honestly, hard to tell exactly what is messed up, but it seems it started happening after 1.06 game update and correlates somehow with what AMD GPU driver does.
I don't own AMD GPU so I'm unable to debug this properly.... Seems like this issue is affecting them in some way, as there seems to be no other correlation at this point in time... And as said, looking at the memory dump of his, it seems to crash in GPU driver, not in our mod...

If I'd have a guess, I believe they must have changed some part of rendering code silently between 1.05 and 1.06 (silently here meaning it is not mentioned at all in patch notes) and that is now causing some weird issues with this mod on AMD hardware.

**Comment by TheChief5055** [comment]
It crashes when CP2077 runs in windowed mode. When CP2077 runs in fullscreen, console works great, with or without AMD Overlay. Well, at least now I can use that wonderful mod of yours, so thanx again.

**Comment by WSSDude420** [comment]
According to one Discord user with AMD gpu that had crashes, latest test build I sent him seems to have helped.

I poked yamashi to create new official build, try it if you can if it helps.

**Comment by helium-three** [comment]
Report from another Discord user, GhostMirror, running AMD Drivers 20.12.1 on RX Vega 56, CET 1.7.2, Reshade, and RTSS in _fullscreen_ mode getting CTD upon opening console. Was advised to run in borderless windowed mode but, instead, disabled Reshade and RTSS which appears to have resolved the issue. GM also reenabled Reshade and RTSS and switched from fullscreen to borderless windowed which also appears to have resolved the issue as expected.

**Comment by DrStalker** [comment]
> According to one Discord user with AMD gpu that had crashes, latest test build I sent him seems to have helped.
> 
> I poked yamashi to create new official build, try it if you can if it helps.
> (NOTE: it is already out, 1.7.2 is the one in question)

Build 1.7.3 fixed the issue for me; using the same settings in my original post and upgrading the CyberEngineTweaks version works fine.  Thank you very much for the fix (and for the tool in general)

**Comment by inkdonkey** [comment]
FPS dropped from 50+ to 1 when activating console(ver 1.7.3)

**Comment by WSSDude420** [comment]
@inkdonkey that is already fixed, wait till next release. Should drop soon.

**Comment by DrStalker** [comment]
Minor update: reinstalling Reshade didn't cause any problems with the 1.7.3 release.
