### ISSUE TITLE
Skip start menu and fullscreen

### ISSUE THREAD

**Issue by NielsGx** [yamashi/CyberEngineTweaks#332]
Any reason why we cannot use "Skip start menu" with exclusive fullscreen ?

I won't go in Borderless, because F borderless. Exclusive fullscreen is superior in every way, especially when it comes to latency.
Who would play a first person shooter with input lag ?
Either find a fix, or make it false by default. Everyone plays in exclusive fullscreen, and skipping 10sec is not worth disabling it..

**Comment by NielsGx** [comment]
By the way, no issue in exclusive fullscreen with the console and debug menu. Commands work.
Skip start menu does, in the contrary, make the game completly frozen. If we alt tab and go back inside CP2077, the frozen image is updated, but immediatly re-frozen.

**Comment by WSSDude420** [comment]
You know what? 

Fix it yourself with that attitude... 🥇 

Sounds like Karen in action reading this 😄

**Comment by NielsGx** [comment]
Don't take that personally, I hate borderless, not you in particular..
I should have put emoji I guess

**Comment by WSSDude420** [comment]
Well, regarding the issue at hand...

It seems there is general issue with how CDPR manages their buffers from what I remember from somwhere... Which is problematic.

Freezing image like you said - found it also, is almost certainly caused by buffer they thrown away when they minimized window (resize happens here) but we are bound to, keeping it alive.
Problem seems to be resizing.

When I think about it, I dont think I tried to change resolution with mod running... Would be interesting test to see if this issue materializes because of it even in windowed/borderless.,..

Anyway, detecting and handling changes like this is a lot of work and requires some better management of resources in general.
Frankly speaking, I don't think this will get ever fully fixed, or if then it won't be so soon, sorry 😞 

There are other more major issues that need fixing first, this is something that can be worked around quite easily.

**Comment by PhantomGamers** [comment]
I play in exclusive fullscreen and have no problem with the skip start screen setting...

**Comment by WSSDude420** [comment]
Me personally neither... There are some true issues with fullscreen currently though, so even though this is something new regarding potential fullscreen issues, making fullscreen to work more reliably should allow for this to work properly.

We have something in mind that could at least help if not directly fix fullscreen issues so we'll see.
