### ISSUE TITLE
[Feature Request] Console UI scaling

### ISSUE THREAD

**Issue by megamanzteam** [yamashi/CyberEngineTweaks#341]
I got the console to work just fine in the first run, yay! However, I am on a 4k tv at 3840x2160 at 60fps and the console while there was too small for me to be able to read anything. So I did encounter a small issue when trying to correct this. I tried to set my game to 1920x1080 borderless and game resolution went wild. It could be CP2077 or this mod, not sure as I haven't tried changing resolutions before this. So the game window became small but did not stretch to a "fullscreen" borderless. I then managed to reset back to 4k and the game was still a tiny window but the 4k was cut off. A restart of the game fixed that part. Obviously fullscreen doesn't work and I think the resolution issue I found is related to issue #193.

Can you add some sort of config option to scale the ui so it isn't so small to read in 4k?

**Comment by MdosTV** [comment]
I wrote a post about this in #329. You should be able to run in full screen, you just need to make sure that the game resolution and you monitor resolution are the same. Also WSSDude420, one of the contributors goes to talk abit about how the UI functions. Hope this helps.

**Comment by WSSDude420** [comment]
A small note - there is no such thing as fullscreen borderless.

Borderless is always windowed mode. Difference between true windowed and borderless is that borderless does not have non-client area which includes things like border, title, minimize/close buttons,...

Lower borderless resolution than monitor resolution would result in smaller window in center of monitor and is expected to happen.

Regarding that resize though, will be fixed with next release.
We have something prepared and are tuning it.
