### ISSUE TITLE
xmake error

### ISSUE THREAD

**Issue by scx1125** [yamashi/CyberEngineTweaks#347]
install lua 5.4.1 .. failed
[0m[38;5;2;1m[ 50%]:[0m [38;5;5;1marchiving.release lua.lib[0m
[0m[38;5;2;1m[ 83%]:[0m [38;5;5;1mlinking.release lua.exe[0m
[0m[1;38;5;1;1merror: [0mLINK : warning LNK4001: 未指定对象文件；已使用库
LINK : fatal error LNK1561: 必须定义入口点
[0m
[0m[1;38;5;3;1mwarning: [38;5;3;1mcannot match target(lualib).add_files("src\*.c|lua.c|luac.c") at .\xmake.lua:5[0m
[0m[1;38;5;3;1mwarning: [38;5;3;1madd -v for getting more warnings ..[0m

**Comment by WSSDude420** [comment]
oh wow how did you manage that?

it can be seen in #345 too so we know whats going on now...

funny thing is that i cannot trigger this on my machine... maybe im just trying to "abuse" xmake in wrong manner...

**Comment by WSSDude420** [comment]
hey, sorry to poke you like this @warugi but you know what may be up with this?

**Comment by waruqi** [comment]
> hey, sorry to poke you like this @waruqi but you know what may be up with this?
> 
> it stopped working recently, like few hours recently.

This is because the https://www.lua.org/ftp/lua-5.4.1.tar.gz link certificate expired, causing curl to fail to download, and xmake automatically switched to the git url source to download its code.

However, the directory structure of the original lua code in the git repo is not exactly the same as the tar package. There is no src subdirectory, and all code files are in the root directory, causing the xmake-repo/lua/xmake.lua#on_install installation process to be interrupted.

I have fixed this package, you can update xmake-repo and try it again.

```console
xmake repo -u
xmake f -c
xmake
```

patch: https://github.com/xmake-io/xmake-repo/commit/b2a161c17ae660dcb00a57e0ec2b19b3ba35f637

>curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328) - The received certificate has expired.
error: execv(curl -SL -A "Xmake/2.3.9+202011250023 (Windows;) curl/7.55.1" https://www.lua.org/ftp/lua-5.4.1.tar.gz -o lua-5.4.1.tar.gz) failed(35)
  => download https://www.lua.org/ftp/lua-5.4.1.tar.gz .. failed
Cloning into 'source.tmp\lua'...

**Comment by WSSDude420** [comment]
Seems to work correctly now.

Tried to force check to run again on linekd PR here.
Also tested this locally, although it did nothing of interest for me (even log was poor).

Looks like that me, having it prolly locally downlaoded already, worked before and now so no change for me personally with this.
Thank you anyway for fixing this though! At least said checks we have in place for PRs are not failling now.

**Comment by scx1125** [comment]
Thanks for your help, the problem has been solved

**Comment by WSSDude420** [comment]
Close the issue then :P
