### ISSUE TITLE
registerInput handler to allow for more regular inputs (KeyDown+KeyUp events)

### ISSUE THREAD

**Issue by seifer7** [yamashi/CyberEngineTweaks#424]
_Amazing work on the new update. Love the new console popup with settings + ability to bind mod keys!_

Testing it out now with the following code:
```
registerHotkey('KEYPRESS_TEST','Test Key Press Event', function()
	print('Key press event fired!')
end)
```

The bind appears in the new console popup and I can bind a key.
If I press the key, I see the message successfully printed in the console, however if I HOLD the key, it only plays the event once.

Is there a way to have it repeat the event?
Otherwise, I think we need a function for "key down" and "key up" so that we can call some function loop over and over until the "key up" function terminates it.

**Comment by seifer7** [comment]
I was thinking something like:
```
test_key_is_down = false;
registerForEvent("onUpdate", function()
	if test_key_is_down == true then
		print("The key bound to KEYPRESS_TEST is currently held down")
	end
end)

registerHotkey('KEYPRESS_TEST','Test Key Press Event', function()
	print('Key down event fired!')
	test_key_is_down = true;
end, function()
	print('Key up event fired!')
	test_key_is_down = false;
end)
```

Where `registerHotkey` is defined as:
`registerHotkey(<bind id>,<bind description>,<key down callback function>,<key up callback function>)`

Running this in game would result in the console printing the following messages:
```
Key down event fired!
The key bound to KEYPRESS_TEST is currently held down
The key bound to KEYPRESS_TEST is currently held down
The key bound to KEYPRESS_TEST is currently held down
The key bound to KEYPRESS_TEST is currently held down
The key bound to KEYPRESS_TEST is currently held down
Key up event fired!
```

Obviously the messages would repeat for as long as the key is held down.

**Comment by seifer7** [comment]
PS. Sorry for making Issues without contributing a pull request. I tried looking into how the key press events work but I'm not good with `C++` programming. I code in PHP/JS.

**Comment by yamashi** [comment]
That's a reasonable request, we will implement something for this in the next version :)

**Comment by WSSDude420** [comment]
Yes, was planned just didnt got in in time...

Proper sandboxing is something we have as higher priority now I'd say, as that is something which is just needed to be done ASAP IMO.

registerInput will function for single keys and will allow this, will look same, but handler will have bool param saying if key was down or up.

So you could, thanks to param, detect input state.

This will never get there for HK due to way they work. Cannot be done.

**Comment by WSSDude420** [comment]
Single-key inputs handler, could be done as enhancement to existing VKBindings system, probably by extending it to use uint64_t instead of uint32_t for code point and having each key stored in word instead of byte.
This would also allow us to have maybe some extra flags and such for controller in the future, which could prove interesting.

This handler should be called twice - once registered key is pressed and once it is released, passing this info into mod (some boolean parameter probably).
