### ISSUE TITLE
1.11 Crash whenever alt-tabbing

### ISSUE THREAD

**Issue by petex8989** [yamashi/CyberEngineTweaks#448]
Whenever I alt-tab, the game crashes immediately. I have had this issue with prior builds.

i7-8700k/ 32GB RAM DDR4 / 2080ti / Windows 10 pro

**Comment by nodeg** [comment]
I **cannot** confirm this issue. 

- Cyberpunk 2077 Hotfix 1.11
- CET 1.9.5
- Radeon RX 580
- Intel i7-3770

Tabbing out works. I had this issue before version1.9.5 but could fix it by pressing ESC to land in the menu and then tabbing out.

**Comment by northaxosky** [comment]
Same here - i9 9900k - 32 GB RAM - 2080Ti

**Comment by lorcalhost** [comment]
Same here:
- Cyberpunk 2077 _Hotfix 1.11_
- CET _v1.9.6_
- Unlock Night City mod _v1.5.0_


Specs:
- Ryzen 5 3600XT 
- 16GB RAM 
- 3070

**Comment by WSSDude420** [comment]
Did you try to test this without mods? :) 

We are not responsible for mods doing shit. There seems to be no proof of clean CET crashing at this point in time.
Always caused by some other overlay/hooking software doing shit with our hooks OR bad mods.

If you can replicate it with absolutely clean install of CET with no mods, good. But this is almost certainly not our issue.

**Comment by lorcalhost** [comment]
@WSSDude420 I was able to reproduce it with no mod installed, this time:
- Cyberpunk 2077 Hotfix 1.12
- CET v1.10.0

I'm not sure where I can get the crash report from but I'll be happy to share

**Comment by WSSDude420** [comment]
Crash reports are in `%TEMP%\..\REDEngine\ReportQueue` (paste this into Windows Explorer adress field, it should open right directory).

Download attached build (is same as 1.10.1, just build in debug so there is some more info involved), let the game crash, **DONT CLICK ON ANYTHING IN CRASH REPORTER**, navigate to folder I wrote about above, package and upload somewhere latest crash report there (should be last one).

Also throw in `cyber_engine_tweaks.log`, maybe something useful will be there too (this sits in `<Cyberpunk root>/bin/x64/plugins/cyber_engine_tweaks`)

[cyber_engine_tweaks.zip](https://github.com/yamashi/CyberEngineTweaks/files/5937448/cyber_engine_tweaks.zip)

**Comment by lorcalhost** [comment]
Sent a zip file on discord.

**Comment by WSSDude420** [comment]
Solved issue for @lorcalhost on Discord.

Issue was linked to #356
This comment (specifically, tweak mentioned in Edit: part) helped the user solve this problem
https://github.com/yamashi/CyberEngineTweaks/issues/356#issuecomment-755124383

**Comment by lorcalhost** [comment]
@WSSDude420 managed to help me find the culprit.
NZXT CAM's `Graphics Hook64.dll` was interfering.

## Fix
- Open NZXT Cam
- Click on `Settings`
![image](https://user-images.githubusercontent.com/9640455/107129999-e5ea8800-68c9-11eb-9e43-45e31aace0f0.png)
- In the `General` section scroll down util you find `Enable Game Hooking`
- Uncheck the tickbox so that it looks like this:
![image](https://user-images.githubusercontent.com/9640455/107130021-13373600-68ca-11eb-9752-87d62afcdbb8.png)
