### ISSUE TITLE
Is the new release backward compatible?

### ISSUE THREAD

**Issue by The-DarkMatter** [yamashi/CyberEngineTweaks#450]
I'm still on 1.06 and don't wanna update the game to 1.1 yet. I want to know if the latest release is backward compatible. I'm sorry that I'm putting this in the Issues section, but I don't know where my questions can be answered.

**Comment by WSSDude420** [comment]
Is not, only latest version. We cannot keep support for all game versions.

**Comment by Si13n7** [comment]
I don't think that's the full truth, older versions were supported once and are still part of the code:
https://github.com/yamashi/CyberEngineTweaks/blob/master/src/Image.cpp#L13

Instead of preventing it hard, it would be nice to display a notification (e. g. MessageBox before game start) for older game versions that CET is always being developed for the latest version of the game, that older versions are may be unstable, lead to crashes, or may not even run in the first place, and that any issue for older versions are ignored.

I play the newest version myself (because of Steam), but the updates after 1.06 brought more problems than they solved and the graphics and performance are also worse for most players. Therefore, players who do not install every update immediately should not be excluded this way. `At your own risk` might be the better way.

**Comment by yamashi** [comment]
It's not about may or may not run, they won't run period.

We don't let the mod load and put an error in the log, an error message would be too invasive.
