### ISSUE TITLE
Teleport to Sebastion Padre black screen bug

### ISSUE THREAD

**Issue by pussnbootlp** [yamashi/CyberEngineTweaks#479]
I think video be better than a thousand meow from me, upload it to my unlisted youtube
[https://youtu.be/DyPs2x0dilU](url)

In my simple words, the game goes black screen if I teleport to Padre. 
I'm using this version: Telemetry-107-1-10-2-1612738535 from Nexus, unable to upgrade to the current version(1.10.3) since it won't even start the CET when the game launch.

**Comment by WSSDude420** [comment]
Game may not launch with newer version cause of mods breaking it. 

Try clean-install of latest release here on GitHub (last one is from like an hour ago if not less). 
If clean install doesnt work (meaning completely removing old version of CET along with potentially outdated mods and installing new version), then we may have a problem. 

But this as a whole (including update and mods misbehaving) may be simply caused by an outdated mod.

If issues persist on latest CET after clean install (note latest one), post log here please.
Can be found in `CP77/bin/x64/plugins/cyber_engine_tweaks.log` .

**Comment by WSSDude420** [comment]
Actually, this seems totally unrelated in general to CET as a whole.

What you have shown seems to be issue with mod, not with us. I would contact mod author of SimpleMenu.
We are not responsible for user mods. We are just platform of sorts for them.

But as you mentioned issues with using latest CET build, I hope we can at least deal with this, even though that will not help you with the mod situation you have at hand probably.
