### ISSUE TITLE
Keyboard and mouse input interrupt after the last patch!

### ISSUE THREAD

**Issue by LittleZen** [yamashi/CyberEngineTweaks#484]
I don't know why, but installing CyberTweaks in my CP2077 cause a strange bug: the keyboard/mouse input stop working in in-game window (i still have control in my os, so i can easy quit the game by task manager, but i can not used the patch anymore :( Some else found that bug too ?

**Comment by shelterx** [comment]
This happens if you have MSI Afterburner/Rivatuner Statistics server running. Close them and you should be good.

**Comment by LittleZen** [comment]
@shelterx Thank you for the reply! I was aware about that, i closed both AB and Rivia statistics, still no have input by keyboard / mouse ... i also tried to turn off my controller, but the game still doesn't accept the input
https://prnt.sc/zle70a

**Comment by WSSDude420** [comment]
It doesnt have to necessarily be just overlays. Any DX12 hook is an issue. These can be frame limiters, monitoring software, overlays, other plugins,... Like there are more options than just overlays :P

Dont know what kinds of softs you have, but I would try disabling overlay everywhere for start.

Discord, GOG, Steam, Nvidia, AMD... Anything which has overlay, check if it is disabled. 
If the popup then renders properly, you can try activating them back on to see which one causes the issues.

There was also some strange issue which we did not found out the cause yet I believe... Some users report running CP77 as admin allows overlay to render when everything else failed, which is strange because we do not for sure require admin rights to function. But is worth a try too.

**Comment by LittleZen** [comment]
@WSSDude420 thanks for the reply! I've tried everything (even a clear restart)... still blocked :/

**Comment by WSSDude420** [comment]
that is surely steange to say the least... post log maybe? something may not be loading right, although this was never really the case.

should be inside plugins/cyber_engine_tweaks/cyber_engine_tweaks.log

**Comment by LittleZen** [comment]
[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/5990097/cyber_engine_tweaks.log)
Attached !

**Comment by LittleZen** [comment]
Seems fixed within the latest version ... dunno why ... CLOSED!

**Comment by WSSDude420** [comment]
Im sorry, I honestly thought I answered you on that log...

I probably just didnt send it for some reason...

Well, at least it kind of solved itself x)

Still dont understand honestly what went wrong (was writting sth like this as a reply).
Log looked clean and nothing seemed failling so my guess was some outside influence (which it could have very well been).

Maybe what helped wasnt really CET update but update of like system or some other application? If this is not a possibility than I dont really get what was wrong and we prolly wont find out anymore...

**Comment by LittleZen** [comment]
@WSSDude420 i didn't really understood how it works ... but in the end ... it works! I've reset the enable/disable overlay button, and seems work fine. I also killed Rivia and MSI AB from the task manager where i closed all the processes related to this two program :/
