### ISSUE TITLE
`version` stopped working again on Linux

### ISSUE THREAD

**Issue by Davoodeh** [yamashi/CyberEngineTweaks#601]
Arch `Linux 5.13.12-arch1-1`
nvidia `470.63.01-3`
Cyberpunk `1.3`
CET `1.61.1`

The game works as expected.
But as soon as I toggle the `version` in `winecfg` game "flatlines".
Without that option in the `winecfg` CET won't get activated and game just normally boots.
Tested with `vc_x64` version `14.28.3033` (or something like that) and `14.29.30133` (Both the one `winetricks` provides and the one in the "Troubleshooting" menu). Neither worked...

The game used to work with the mod perfectly, with CET `1.12.1`... 

If more logs are needed or something please leave the address of the file and I'll fetch it.

**Comment by WSSDude420** [comment]
Noone from us runs this on Linux and we do not provide support for it...
But will keep this open, maybe someone who uses it there will know of something...

Usually though, these get somehow resolved on their own 😄 
Like he comes, asks, and like few hours later is like oh nvm, it fixed somehow 🤷

**Comment by Davoodeh** [comment]
Ironically, it actually got fixed without me doing ANYTHING.
I was playing around with Willy's files and the game just booted up and worked.

It is worth noting that I had the plan of testing the cached CPP files that he provided.
the tree with the versions are here:
```
Package Cache
├── {0093C20C-273D-4397-B623-515CB8616CB9}v14.22.27821
│   └── packages
│       └── vcRuntimeMinimum_amd64
│           ├── cab1.cab
│           └── vc_runtimeMinimum_x64.msi
├── {1E6FC929-567E-4D22-9206-C5B83F0A21B9}v14.22.27821
│   └── packages
│       └── vcRuntimeMinimum_x86
│           ├── cab1.cab
│           └── vc_runtimeMinimum_x86.msi
├── {33d1fd90-4274-48a1-9bc1-97e33d9c2d6f}
│   ├── state.rsm
│   └── vcredist_x86.exe
├── {37B8F9C7-03FB-3253-8781-2517C99D7C00}v11.0.61030
│   └── packages
│       └── vcRuntimeAdditional_amd64
│           ├── cab1.cab
│           └── vc_runtimeAdditional_x64.msi
├── {3BDE80F7-7EC9-448E-8160-4ADA0CDA8879}v14.22.27821
│   └── packages
│       └── vcRuntimeAdditional_x86
│           ├── cab1.cab
│           └── vc_runtimeAdditional_x86.msi
├── {5bfc1380-fd35-4b85-9715-7351535d077e}
│   ├── state.rsm
│   └── VC_redist.x86.exe
├── {6361b579-2795-4886-b2a8-53d5239b6452}
│   ├── state.rsm
│   └── VC_redist.x64.exe
├── {6E2C7A8E-B17A-4637-9CE9-F0B1157CF378}v14.22.27821
│   └── packages
│       └── vcRuntimeAdditional_amd64
│           ├── cab1.cab
│           └── vc_runtimeAdditional_x64.msi
├── {B175520C-86A2-35A7-8619-86DC379688B9}v11.0.61030
│   └── packages
│       └── vcRuntimeAdditional_x86
│           ├── cab1.cab
│           └── vc_runtimeAdditional_x86.msi
├── {BD95A8CD-1D9F-35AD-981A-3E7925026EBB}v11.0.61030
│   └── packages
│       └── vcRuntimeMinimum_x86
│           ├── cab1.cab
│           └── vc_runtimeMinimum_x86.msi
├── {ca67548a-5ebe-413a-b50c-4b9ceb6d66c6}
│   ├── state.rsm
│   └── vcredist_x64.exe
└── {CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}v11.0.61030
    └── packages
        └── vcRuntimeMinimum_amd64
            ├── cab1.cab
            └── vc_runtimeMinimum_x64.msi
```

This is not related to CET but regardless if you run the game on a toaster like me beware
that the performance is still very poor. The game doesn't crash in long sessions like before and textures don't go un-rendered/misplaced. However, there are constant micro-glitches especially when a new sound or texture is introduced to the scene. The average FPS is around 20 (didn't measure just guessing) on the lowest settings 720p with "General Optimization" and No Antialiasing and Static Texture Scaling 50%. With the same GTX 1050 I get a solid 24+ with Medium-High settings and Dynamic Texture Scaling.

Once again thanks to Willy-JL, WSSDude420 and all the other ones :D'

**Comment by Willy-JL** [comment]
Even though you closed this issue, I'll share what solved everything for me, and why we probably were not having the same root problem.
After painfully re-downloading the game for the fourth time using my atrocious 3mbps connection I decided to not risk anything anymore, so I cached the download with Lutris so that I could reinstall easily and then, after installing, I setup a git repo in my install folder so that anytime I try something and it breaks, I can see what changed in the files and also rollback very easily.
 So then:
 - Install game - game runs fine
 - Install redscript - game runs fine, redscript compiles fine
 - Install `vcrun2019` with winetricks from Lutris
 - Game stops working. No flatline, no useful logs, just nothing.
 - Try removing `vcrun2019` using winetricks'  uninstaller feature
 - Still nothing

At this point I am very thankful for the git repo I setup, so I restore to the working redscript commit, and the game starts working again. Then I tried installing CET as usual, just simply skipping the `vcrun2019` part:
 - Drop files where they belong
 - Game still works, no CET however
 - Run winecfg and add `version` library
 - Game works, and I get greeted by CET overlay

So in the end my issues were not related to some strange magic that Steam does with their prefixes. Simply put the tutorial for installing in proton is outdated / is not always needed, and can even completely brick the game. Should probably modify it to state clearly to ONLY try installing `vcrun2019` as a last resort, or at least to check if the mod works without installing it.

Oh, should also that at first I was experiencing huge memory leaks, as in I couldn't even reach the main menu without `nohang` killing cp77. I "fixed" that by downgrading my `nvidia`, `nvidia-utils` and `nvidia-dkms` to versions `465.x`, since `470.x` is known for causing said memory leaks with Vulkan. It's "fixed" because while now Cyberpunk and Horizon Zero Dawn work fine, Steam refuses to boot up...

**Comment by Davoodeh** [comment]
Oh man, once again your genius methods worked.
You are right. I guess "I did nothing and work" is literally what I did. Maybe I just forgot to enable `vcrun2019` verb this time around.

Didn't test the `465.x` for FPS issue tho.

**Comment by edmondo** [comment]
@Willy-JL thanks for sharing the hints.

I'm using Proton Experimental and I didn't need to install the vcrun2019.
Just download CET, unpack and change the launch options in Steam.

- Unpack:

`~/.local/share/Steam/steamapps/common/Cyberpunk 2077 $ 7z x ~/Downloads/Cyber\ Engine\ Tweaks-107-1-17-1-1633187938.zip`

- Steam Launch Options with native version.dll override:

`WINEDLLOVERRIDES="version=n,b" %command% --launcher-skip -skipStartScreen`
