### ISSUE TITLE
Cyberpunk (v1.31) will crash if graphics are higher than "low"

### ISSUE THREAD

**Issue by aghebert** [yamashi/CyberEngineTweaks#621]
I have narrowed down the issue to CET as the problem doesn't occur in vanilla Cyberpunk and tested it on both 1.17.1 and 1.16.4. I tried testing different settings but nothing seems to work: If I change the graphics higher than "low" at the start menu, then start the game it crashes; if I change graphic quality midgame it crashes immediately.

**Comment by eshjordan** [comment]
I have the same issue with the default CET config, not able to launch to the start menu if the graphics settings are above "low". I did find that setting `"disable_async_compute":` false` in CET's config.json file allowed me to launch into the start menu though. I'm running an AMD Ryzen CPU with an GTX1080

**Comment by nerodevo** [comment]
- Running game version 1.5001 (hotfix patch) and CET 1.19.1-5-g74e9b86 [master].
- Game graphics quick preset set to Custom
- Texture Quality set to High and other graphic settings set to either High or Ultra
- I git clone CTE plus dependencies (RED4ext.SDK, xbyak, stb) and build the project (xmake -y) using VS2022 x64_x86 Cross-tools command environment with some modifications due some build issues related to the recent additions of xbyak and stb packages. During game v1.31, I could just use VS2022 x64 command environment and it would work without issue.

I originally had "disable_async_compute" set to false because of the crashing as well. I decided to try setting it to true again and now it's not crashing. Posted my log and config (added txt extension for attaching).
[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/8134211/cyber_engine_tweaks.log)
[config.json.txt](https://github.com/yamashi/CyberEngineTweaks/files/8134219/config.json.txt)

**Comment by WSSDude420** [comment]
I have a feel this is an old issue which may not be relevant anymore. If it is still present, reopen it with newer info.
