### ISSUE TITLE
First Version of Cyber Engine Tweaks doesn't work with "Cyberpunk2077.exe v1.02"

### ISSUE THREAD

**Issue by lif3mau5** [yamashi/CyberEngineTweaks#643]
Please make a Version for: 
Cyberpunk 2077
Game Vendor: Steam
Game Version: 1.02
Game Process: Cyberpunk2077.exe
File Version: 3.0.48.60909

Thank you for this awesome work!

**Comment by WSSDude420** [comment]
Earliest working version was 1.04
1.02 was never supported.
Also, with such old version, literally none of the mods would work.

**Comment by lif3mau5** [comment]
I hardly believe that you are not able to program a CET for 1.02. I can also provide you with the complete 1.02 release and help with the programming.

**Comment by lif3mau5** [comment]
> Earliest working version was 1.04 1.02 was never supported. Also, with such old version, literally none of the mods would work.

I hardly believe that you are not able to program a CET for 1.02. I can also provide you with the complete 1.02 release and help with the programming.

**Comment by yamashi** [comment]
We just don't care about it, feel free to create a fork for 1.02

**Comment by lif3mau5** [comment]
> We just don't care about it, feel free to create a fork for 1.02

Why are you not interested in the old, initial version, which still contains the content that was removed in later version? I'm currently trying to build the PS4 retail disk (Build_3017731Change_3953367), using the development build source code (1.3), for PC. I would appreciate when some good developers and people were involved in the project. People like Tyler McVicker, DeconstructingTheGame, Ryan LeCocq, Edepot and Sventra have helped me many times, can help and would also help if necessary. I need any help, with the consent of CDPR, if the project is to appear soon and not in 20 years...

**Comment by cglmrfreeman** [comment]
I think you might have better luck with CyberConsole with that early of a version.

**Comment by romulus2k4** [comment]
> Why are you not interested in the old, initial version, which still contains the content that was removed in later version? I'm currently trying to build the PS4 retail disk (Build_3017731Change_3953367), using the development build source code (1.3), for PC. I would appreciate when some good developers and people were involved in the project. People like Tyler McVicker, DeconstructingTheGame, Ryan LeCocq, Edepot and Sventra have helped me many times, can help and would also help if necessary. I need any help, with the consent of CDPR, if the project is to appear soon and not in 20 years...

First off, 1.02 was never released to the public, the earliest version that got released on PC is 1.03.

Second, the PS4 retail disk stuff will not work on PC due to difference in how textures and mesh assets are cooked. IDK if you even know WTF you are doing.

Third, source code 1.3 is stolen asset. Do not expect any help from us with whatever you're planning to do with stolen assets.

Lastly, Tyler McVicker, DeconstructingTheGame, and the rest of the people you've mentioned are not coders. I know at least two of them quite well, and they've probably never heard of you or have interacted with you. They are not coders, and I doubt you have any consent from CDPR whatsoever. So, quit trying to bluff people.

And lastly, Fuck you.
