### ISSUE TITLE
Game immediately crashes when launching with wine on GNU/Linux.

### ISSUE THREAD

**Issue by Kelvium** [yamashi/CyberEngineTweaks#693]
```
wine: wine-tkg 7.12 staging with fsync and esync support (am using fsync)
distro: Gentoo ~amd64 with every required library compiled for multilib wine
kernel: 5.18.14
game: gog 5.52 it says (not sure if 5.52.1)
video card drivers: mesa radv 22.1.3
```

I'm not sure if Linux support is in the goals list of CET. Tried to follow [the guide for Proton](https://wiki.redmodding.org/cyber-engine-tweaks/getting-started/installing/untitled) but with wine, except the winecfg step where we add a new override for 'version' library because it borks the whole wine prefix. I installed vcrun2019 and d3dcompiler_47 via winetricks. Didn't help. That's the crash log (a page fault): [click me :)](https://pastebin.com/6uUmZEhY). I've also tried the [latest at the time CET version for 5.52.1](https://github.com/yamashi/CyberEngineTweaks/releases/tag/v1.19.5) and also [the latest-1 version](https://github.com/yamashi/CyberEngineTweaks/releases/tag/v1.19.4).

Appreciate your work =)

**Comment by WSSDude420** [comment]
CET uses VS2022 now, that is one thing worth trying out I guess (installing its redist instead of VS2019).

Other than that, Linux is hit or miss. Works for some, does not for others, and even if it worked for some, it randomly stops working for no aparent reason (had some reports like these without anything changing, either with the game or in CET).

We do not officially support it because it as it is not maintainable in the above context. Too many different distros/flavours, different libs and package versions, even the same package versions tend to be compiled differently between distros,... Everyone needs to do slightly different things to make it somewhat run.

Page you linked was made by someone from the community around the time release dropped, I bet it was not properly updated since (maybe some typo fixes if even that). We lack experience with Wine/Proton.

You may try to look under closed issues for some other linux-related if there are not some other things to try, but dont expect support from us unfortunately as we cant provide it.
