### ISSUE TITLE
using LogChannel in early callback cause inconsistencies

### ISSUE THREAD

**Issue by Roms1383** [yamashi/CyberEngineTweaks#731]
## description

As it seems after many tests, there's a minor issue with CET console (subsequent logs wouldn't show up anymore after first click on "Clear all logs") and status effects lifecycle / hud get disrupted somehow (top left status bar disappears, health doesn't get regenerated from e.g. maxdoc ..).

## reproduction

Aside from fundamental mods (CET compatible Red Hot Tools, REDscript, TweakXL, Native Settings),
using [Toxicity](https://www.nexusmods.com/cyberpunk2077/mods/4317) and a custom mod like:

📁 r6/scripts/MyMod

     📄 system.reds
     
```reds
module MyMod

public class MyModSystem extends ScriptableSystem {
    private func OnAttach() -> Void {
        // see https://discord.com/channels/717692382849663036/804399334246187038/1038062883860385825
        // ❌ LogChannel(n"DEBUG", "RED:MyModSystem::OnAttach");
    }
}
```
    
     📄 mod.reds
    
```reds
module MyMod

@wrapMethod(PlayerPuppet)
protected cb func OnStatusEffectApplied(evt: ref<ApplyStatusEffectEvent>) -> Bool {
    let container = GameInstance.GetScriptableSystemsContainer(this.GetGame());
    let system = container.Get(n"MyMod.MyModSystem") as MyModSystem;
    return wrappedMethod(evt);
}
```
    
📁 bin/x64/plugins/cyber_engine_tweaks/mods/MyMod

     📄 init.lua

```lua
registerForEvent("onInit", function()
    print("CET:MyMod:onInit")
end)
```

Hope this helps, thanks.

**Comment by WSSDude420** [comment]
onInit should be done on first frame of update before first onUpdate call.
in regards to observes/overrides, there should be some other hook made to prevent issues.

only reason we call onInit where we call it now is because it is earlier place where most things work but game is not yet fully initialized.
and during onInit, it is still possible to call something you shouldn't as of time of writting (one of the reasons for your crash I believe, as you made it to run sooner than expected).

having separate hook just for overrides (akin to onTweak for tweakdb) seems natural and prefered way to fix this probably, as it should solve issue of "not overriding soon enough" and also issue of "using something in onInit when it is not yet available"

**Comment by Roms1383** [comment]
utterly agree! I literally started CET, RED, etc last week for the first time and naively thought `LogChannel` was available in early hook until people in Discord channel rightfully pointed this out.

**Comment by WSSDude420** [comment]
This should be fixed in latest master, will be in next release.
